### ISSUE TITLE
[Bug]: LibreChat error on Docker 

### ISSUE THREAD

**Issue by fuegovic** [danny-avila/LibreChat#1096]
### What happened?

When redirected to /chat/new an error appears on screen and nothing works

It can be tested on huggingface by accessing from this URL: https://librechat-librechat.hf.space/login
For some reasons it seems easier to bypass the error on huggingface. On both of my PCs, LibreChat is impossible to use (from docker)

`npm run backend` works fine, it only affects docker.

### Steps to Reproduce

- from a docker install of LibreChat
1. login
2. refresh the page
3. error 

### Relevant log output

```shell
Unexpected Application Error!
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at Td (http://localhost:3080/assets/index-097ff3ec.js:40:31972)
    at Zv (http://localhost:3080/assets/vendor-9c30f500.js:38:19538)
    at Bx (http://localhost:3080/assets/vendor-9c30f500.js:40:44055)
    at Px (http://localhost:3080/assets/vendor-9c30f500.js:40:39787)
    at kP (http://localhost:3080/assets/vendor-9c30f500.js:40:39715)
    at Fh (http://localhost:3080/assets/vendor-9c30f500.js:40:39568)
    at W9 (http://localhost:3080/assets/vendor-9c30f500.js:40:35933)
    at U3 (http://localhost:3080/assets/vendor-9c30f500.js:40:36737)
    at ks (http://localhost:3080/assets/vendor-9c30f500.js:38:3279)
    at MP (http://localhost:3080/assets/vendor-9c30f500.js:40:41283)
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/32828263/8bae21f1-45c5-4282-816a-4e5c9b8ea912)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Hi @fuegovic  thanks for reporting this!

for these issues, we can debug by using `npm run frontend:dev` when docker is running to get a more informative error. By doing this, I was able to get a solution. This is a weird edge case, since it's specific to network requests to the docker container.

**Comment by fuegovic** [comment]
> for these issues, we can debug by using `npm run frontend:dev` when docker is running...

Thanks for the tips!
