### ISSUE TITLE
[Bug]: cache (meilisearch) and context still captured while endpoint returns error

### ISSUE THREAD

**Issue by shuther** [danny-avila/LibreChat#1285]
### What happened?

My end point (openrouter) was returning an error (You are out of credits.) but I identified while running the docker (latest build) with debug mode than this output was indexed and the different requests (multiple requests with errors as per the chat window) were included in the PAYLOAD/TOKEN COUNT MAP.

### Steps to Reproduce

you need an AI endpoint that will return: You are out of credits:
```
LibreChat         | Error: Error: 402 You are out of credits. Please visit https://openrouter.ai/account to add more.
LibreChat         |     at OpenAIClient.chatCompletion (/app/api/app/clients/OpenAIClient.js:826:15)
LibreChat         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
LibreChat         |     at async OpenAIClient.sendCompletion (/app/api/app/clients/OpenAIClient.js:442:15)
LibreChat         |     at async OpenAIClient.sendMessage (/app/api/app/clients/BaseClient.js:452:24)
LibreChat         |     at async /app/api/server/routes/ask/openAI.js:112:20
```

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
chat-meilisearch  | [2023-12-05T19:47:53Z DEBUG meilisearch::routes::indexes::documents] called with params: AwebQueryParameter(UpdateDocumentsQuery { primary_key: None, csv_delimiter: None }, PhantomData<*const meilisearch_types::deserr::DeserrError<meilisearch_types::deserr::DeserrQueryParam, meilisearch_types::error::deserr_codes::BadRequest>>)
chat-meilisearch  | [2023-12-05T19:47:53Z DEBUG actix_web::middleware::logger] Error in response: ResponseError { code: 404, message: "Document `29335dd0-c006-4d36-a643-a871204b1a0d` not found.", error_code: "document_not_found", error_type: "invalid_request", error_link: "https://docs.meilisearch.com/errors#document_not_found" }
chat-meilisearch  | [2023-12-05T19:47:53Z INFO  actix_web::middleware::logger] 172.26.0.4 "GET /indexes/convos/documents/29335dd0-c006-4d36-a643-a871204b1a0d HTTP/1.1" 404 189 "-" "undici" 0.000601
LibreChat         | [Meilisearch] Convo not found and will index 29335dd0-c006-4d36-a643-a871204b1a0d
chat-meilisearch  | [2023-12-05T19:47:53Z DEBUG meilisearch::routes::indexes::documents] called with params: AwebQueryParameter(UpdateDocumentsQuery { primary_key: None, csv_delimiter: None }, PhantomData<*const meilisearch_types::deserr::DeserrError<meilisearch_types::deserr::DeserrQueryParam, meilisearch_types::error::deserr_codes::BadRequest>>)
chat-meilisearch  | [2023-12-05T19:47:53Z DEBUG meilisearch::routes::indexes::documents] returns: Task { uid: 13, enqueued_at: 2023-12-05 19:47:53.459059807 +00:00:00, started_at: None, finished_at: None, error: None, canceled_by: None, details: Some(DocumentAdditionOrUpdate { received_documents: 1, indexed_documents: None }), status: Enqueued, kind: DocumentAdditionOrUpdate { index_uid: "messages", primary_key: None, method: ReplaceDocuments, content_file: 2bc3dffa-2757-4654-9fb9-51c74c3fcc51, documents_count: 1, allow_index_creation: true } }
chat-meilisearch  | [2023-12-05T19:47:53Z INFO  actix_web::middleware::logger] 172.26.0.4 "POST /indexes/messages/documents HTTP/1.1" 202 136 "-" "undici" 0.015734
LibreChat         | baseURL https://openrouter.ai/api/v1
chat-meilisearch  | [2023-12-05T19:47:53Z DEBUG index_scheduler::batch] update: RemapDocumentAddition { documents_seen: 0 }

LibreChat         | Error: Error: 402 You are out of credits. Please visit https://openrouter.ai/account to add more.
LibreChat         |     at OpenAIClient.chatCompletion (/app/api/app/clients/OpenAIClient.js:826:15)
LibreChat         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
LibreChat         |     at async OpenAIClient.sendCompletion (/app/api/app/clients/OpenAIClient.js:442:15)
LibreChat         |     at async OpenAIClient.sendMessage (/app/api/app/clients/BaseClient.js:452:24)
LibreChat         |     at async /app/api/server/routes/ask/openAI.js:112:20
chat-meilisearch  | [2023-12-05T19:47:54Z DEBUG meilisearch::routes::indexes::documents] called with params: AwebQueryParameter(UpdateDocumentsQuery { primary_key: None, csv_delimiter: None }, PhantomData<*const meilisearch_types::deserr::DeserrError<meilisearch_types::deserr::DeserrQueryParam, meilisearch_types::error::deserr_codes::BadRequest>>)
chat-meilisearch  | [2023-12-05T19:47:54Z DEBUG meilisearch::routes::indexes::documents] returns: Task { uid: 15, enqueued_at: 2023-12-05 19:47:54.014080133 +00:00:00, started_at: None, finished_at: None, error: None, canceled_by: None, details: Some(DocumentAdditionOrUpdate { received_documents: 1, indexed_documents: None }), status: Enqueued, kind: DocumentAdditionOrUpdate { index_uid: "messages", primary_key: None, method: ReplaceDocuments, content_file: e60ab2f2-4cd9-4f29-97c0-95966bca73e1, documents_count: 1, allow_index_creation: true } }
chat-meilisearch  | [2023-12-05T19:47:54Z INFO  actix_web::middleware::logger] 172.26.0.4 "POST /indexes/messages/documents HTTP/1.1" 202 136 "-" "undici" 0.012510
chat-meilisearch  | [2023-12-05T19:47:54Z DEBUG index_scheduler::batch] update: RemapDocumentAddition { documents_seen: 0 }
chat-meilisearch  | [2023-12-05T19:47:54Z DEBUG index_scheduler::batch] update: RemapDocumentAddition { documents_seen: 1 }
chat-meilisearch  | [2023-12-05T19:47:54Z DEBUG index_scheduler::batch] update: RemapDocumentAddition { documents_seen: 1 }
chat-meilisearch  | [2023-12-05T19:47:54Z DEBUG index_scheduler::batch] update: ComputeIdsAndMergeDocuments { documents_seen: 1, total_documents: 1 }

LibreChat         | Token Count Map: {
LibreChat         |   'e24a99cc-02a4-48b8-9a30-3a48d6bf802f': 23,
LibreChat         |   '65d4f8c3-d5f3-486e-85fe-0c44c9ebbbca': 26,
LibreChat         |   '62fa211d-4524-4613-bf97-db0ded4f96ac': 25
LibreChat         | }
LibreChat         | Prompt Tokens 77 remainingContextTokens 4018 this.maxContextTokens 4095
LibreChat         | {
LibreChat         |   'e24a99cc-02a4-48b8-9a30-3a48d6bf802f': 23,
LibreChat         |   '65d4f8c3-d5f3-486e-85fe-0c44c9ebbbca': 26,
LibreChat         |   '62fa211d-4524-4613-bf97-db0ded4f96ac': 25,
LibreChat         |   instructions: undefined
LibreChat         | }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Triage note on a 2.7-year-old report. @danny-avila confirmed the intent back in 2023 (failed responses should not be indexed or token-counted), but I cannot verify the behavior against current main: every code path in your trace (`api/app/clients/OpenAIClient.js`, `api/app/clients/BaseClient.js`, `api/server/routes/ask/openAI.js`) no longer exists. That client layer was rewritten around `packages/api` and the agents runtime in the meantime.

@shuther if you are still running LibreChat, could you confirm on a current version (v0.8.x)?

- LibreChat version and deployment method
- whether a failed provider request (for example a 402 or 401) still creates a MeiliSearch document
- whether the failed turn still appears in the token count map

Leaving this open pending that detail. Tagging with the question label because this repo has no needs-info label.

Classification: bug, severity medium (token accounting accuracy plus search index pollution), priority low until reproduced on a current build.
