### ISSUE TITLE
[Bug]: Compose v1 fails

### ISSUE THREAD

**Issue by OdinGitDat** [danny-avila/LibreChat#1735]
### What happened?

The 'npm run update' command fails because it uses Compose v1, this version does not support all override features e.g. !reset tag.

This is my docker-compose.override.yml:
```
services:
  api:
    ports: !reset []
```
The `docker-compose down` (v1) command fails, but `docker compose down` (v2) works fine.

This project should be using Compose v2 everywhere to enable all override features.

### Steps to Reproduce

1. Set override.yml as above
2. Run 'npm run update'
3. Observe error

### Relevant log output

```shell
> LibreChat@0.6.6 update
> node config/update.js

Are you using Docker? (y/n):
> y
Are you using the default docker-compose file? (y/n):
> y
Starting update script, this may take a minute or two depending on your system and network.
Fetching the latest repo...
Switching to main branch...
Already on 'main'
Your branch is up to date with 'origin/main'.
Pulling the latest code from main...
From https://github.com/danny-avila/LibreChat
 * branch              main       -> FETCH_HEAD
Already up to date.
Removing previously made Docker container...
docker-compose down
ERROR: yaml.constructor.ConstructorError: could not determine a constructor for the tag '!reset'
  in "./docker-compose.override.yml", line 75, column 12
(node:297635) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose down
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at /home/odin/LibreChat/config/update.js:86:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:297635) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:297635) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks I’ll update the scripts to use v2
