### ISSUE TITLE
[Bug]: Generating images using Image prompt enhancer and DALL-E(-3) via Czech prompts doesn't work

### ISSUE THREAD

**Issue by ceskyDJ** [danny-avila/LibreChat#2283]
### What happened?

Hi, thanks for a great app! I noticed a pretty weird bug, when I try some prompts in Czech language. When I use Image prompt enhancer and DALL-E plugins, it just doesn't work. The error message is a little cryptic for me, so I don't know what cause it could have. Could you look at it, please?

### Steps to Reproduce

1. Create new chat with gpt-4-turbo-preview
2. Add and activate plugin DALL-E or DALL-E-3 with Image promp enhancer at the same time
3. Give it some prompt **in Czech** for generating image, e.g. "Vygeneruješ mi prosím obrázek typický pro Českou republiku?"
4. It ends with an error "Something went wrong. Here's the specific error message we encountered: Encountered an error while attempting to respond: output values have 2 keys, you must specify an output key or pass only 1 key as output"

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{"level":"error","message":"[PluginsClient] executorCall error: output values have 2 keys, you must specify an output key or pass only 1 key as output","stack":"Error: output values have 2 keys, you must specify an output key or pass only 1 key as output\n    at getOutputValue (/app/node_modules/@langchain/core/dist/memory.cjs:46:15)\n    at BufferMemory.saveContext (/app/node_modules/@langchain/community/dist/memory/chat_memory.cjs:53:77)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AgentExecutor.call (/app/node_modules/langchain/dist/chains/base.cjs:136:13)\n    at async PluginsClient.executorCall (/app/api/app/clients/PluginsClient.js:185:23)\n    at async PluginsClient.sendMessage (/app/api/app/clients/PluginsClient.js:329:5)\n    at async /app/api/server/routes/ask/gptPlugins.js:164:22"}
{"level":"error","message":"[PluginsClient] executorCall error: output values have 2 keys, you must specify an output key or pass only 1 key as output","stack":"Error: output values have 2 keys, you must specify an output key or pass only 1 key as output\n    at getOutputValue (/app/node_modules/@langchain/core/dist/memory.cjs:46:15)\n    at BufferMemory.saveContext (/app/node_modules/@langchain/community/dist/memory/chat_memory.cjs:53:77)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AgentExecutor.call (/app/node_modules/langchain/dist/chains/base.cjs:136:13)\n    at async PluginsClient.executorCall (/app/api/app/clients/PluginsClient.js:185:23)\n    at async PluginsClient.sendMessage (/app/api/app/clients/PluginsClient.js:329:5)\n    at async /app/api/server/routes/ask/gptPlugins.js:164:22"}
{"level":"error","message":"[PluginsClient] executorCall error: output values have 2 keys, you must specify an output key or pass only 1 key as output","stack":"Error: output values have 2 keys, you must specify an output key or pass only 1 key as output\n    at getOutputValue (/app/node_modules/@langchain/core/dist/memory.cjs:46:15)\n    at BufferMemory.saveContext (/app/node_modules/@langchain/community/dist/memory/chat_memory.cjs:53:77)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AgentExecutor.call (/app/node_modules/langchain/dist/chains/base.cjs:136:13)\n    at async PluginsClient.executorCall (/app/api/app/clients/PluginsClient.js:185:23)\n    at async PluginsClient.sendMessage (/app/api/app/clients/PluginsClient.js:329:5)\n    at async /app/api/server/routes/ask/gptPlugins.js:164:22"}
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/48548230/61c9e710-b491-43ab-9f98-681187fc84ec)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ceskyDJ** [comment]
Maybe it's good to explicitly say that the same configuration works with English prompts.
