### ISSUE TITLE
[Bug]: When using the assistant, I get an "Unexpected Application Error" when trying to set a preset.

### ISSUE THREAD

**Issue by SuperSandyman** [danny-avila/LibreChat#2804]
### What happened?

Where the LLM type is toggled above (e.g., where it says OpenAI, Google, Plugins), I set it to Assistants. When I tried to set a preset by pressing the settings symbol next to it, "Unexpected Application Error" was displayed.

### Steps to Reproduce

1. clone the project 2. cp .env .env.example
2. cp .env .env.example
3. Activate the Assistant
4. Set API Key of Assistants in .env
5. npm run start:deployed

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Mobile (Android)

### Relevant log output

```shell
Unexpected Application Error!
(r[(l ?? "")] ?? []).map is not a function or its return value is not iterable
TypeError: (r[(l ?? "")] ?? []).map is not a function or its return value is not iterable
    at http://localhost:3080/assets/index-8_nOrTNC.js:51:21349
    at Object.useMemo (http://localhost:3080/assets/vendor-DGHO_bpv.js:38:25964)
    at react_production_min.useMemo (http://localhost:3080/assets/vendor-DGHO_bpv.js:9:7273)
    at Zs (http://localhost:3080/assets/index-8_nOrTNC.js:51:21316)
    at Nh (http://localhost:3080/assets/vendor-DGHO_bpv.js:38:18933)
    at Vk (http://localhost:3080/assets/vendor-DGHO_bpv.js:40:48633)
    at Uk (http://localhost:3080/assets/vendor-DGHO_bpv.js:40:43881)
    at Tk (http://localhost:3080/assets/vendor-DGHO_bpv.js:40:43804)
    at Ik (http://localhost:3080/assets/vendor-DGHO_bpv.js:40:43644)
    at Nk (http://localhost:3080/assets/vendor-DGHO_bpv.js:40:39610)
```

### Screenshots

![スクリーンショット_20-5-2024_234445_localhost](https://github.com/danny-avila/LibreChat/assets/66544945/acb4286e-adf3-4e53-b2bf-e399b8b5db4c)

![スクリーンショット_20-5-2024_234346_localhost](https://github.com/danny-avila/LibreChat/assets/66544945/3f6c4cd0-04b9-4956-9a4d-610c7f86edd3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Thanks! Pushing a fix soon: https://github.com/danny-avila/LibreChat/pull/2805
