### ISSUE TITLE
[Bug]: docker-compose up get  Error: Cannot find module 'firebase/storage'

### ISSUE THREAD

**Issue by SailFlorve** [danny-avila/LibreChat#2948]
### What happened?

LibreChat         | > LibreChat@0.7.2 backend
LibreChat         | > NODE_ENV=production node api/server/index.js
LibreChat         | 
LibreChat         | node:internal/modules/cjs/loader:1148
LibreChat         |   throw err;
LibreChat         |   ^
LibreChat         | 
LibreChat         | Error: Cannot find module 'firebase/storage'
LibreChat         | Require stack:
LibreChat         | - /app/api/server/services/Files/Firebase/crud.js
LibreChat         | - /app/api/server/services/Files/Firebase/index.js
LibreChat         | - /app/api/server/services/Files/strategies.js
LibreChat         | - /app/api/strategies/process.js
LibreChat         | - /app/api/strategies/googleStrategy.js
LibreChat         | - /app/api/strategies/index.js
LibreChat         | - /app/api/server/index.js
LibreChat         |     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
LibreChat         |     at Module._resolveFilename (/app/node_modules/module-alias/index.js:49:29)
LibreChat         |     at Module._load (node:internal/modules/cjs/loader:986:27)
LibreChat         |     at Module.require (node:internal/modules/cjs/loader:1233:19)
LibreChat         |     at require (node:internal/modules/helpers:179:18)
LibreChat         |     at Object.<anonymous> (/app/api/server/services/Files/Firebase/crud.js:5:71)
LibreChat         |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
LibreChat         |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
LibreChat         |     at Module.load (node:internal/modules/cjs/loader:1208:32)
LibreChat         |     at Module._load (node:internal/modules/cjs/loader:1024:12) {
LibreChat         |   code: 'MODULE_NOT_FOUND',
LibreChat         |   requireStack: [
LibreChat         |     '/app/api/server/services/Files/Firebase/crud.js',
LibreChat         |     '/app/api/server/services/Files/Firebase/index.js',
LibreChat         |     '/app/api/server/services/Files/strategies.js',
LibreChat         |     '/app/api/strategies/process.js',
LibreChat         |     '/app/api/strategies/googleStrategy.js',
LibreChat         |     '/app/api/strategies/index.js',
LibreChat         |     '/app/api/server/index.js'
LibreChat         |   ]
LibreChat         | }
LibreChat         | 
LibreChat         | Node.js v20.14.0
LibreChat exited with code 1

### Steps to Reproduce

//

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SailFlorve** [comment]
LibreChat         | node:internal/modules/cjs/loader:1148
LibreChat         |   throw err;
LibreChat         |   ^
LibreChat         | 
LibreChat         | Error: Cannot find module 'dotenv'
LibreChat         | Require stack:
LibreChat         | - /app/api/server/index.js
LibreChat         |     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
LibreChat         |     at Module._load (node:internal/modules/cjs/loader:986:27)
LibreChat         |     at Module.require (node:internal/modules/cjs/loader:1233:19)
LibreChat         |     at require (node:internal/modules/helpers:179:18)
LibreChat         |     at Object.<anonymous> (/app/api/server/index.js:1:1)
LibreChat         |     at Module._compile (node:internal/modules/cjs/loader:1358:14)
LibreChat         |     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
LibreChat         |     at Module.load (node:internal/modules/cjs/loader:1208:32)
LibreChat         |     at Module._load (node:internal/modules/cjs/loader:1024:12)
LibreChat         |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
LibreChat         |   code: 'MODULE_NOT_FOUND',
LibreChat         |   requireStack: [ '/app/api/server/index.js' ]
LibreChat         | }
LibreChat         | 
LibreChat         | Node.js v20.14.0
