### ISSUE TITLE
[Question]: Receiving a connection error while connecting to Ollama on my host machine

### ISSUE THREAD

**Issue by joelclimbsthings** [danny-avila/LibreChat#2961]
### What is your question?

I've been trying to get my local instance of Ollama to work with LibreChat for a while to no avail. I'll post my `librechat.yml` file in the "More Details" section below. I'm runng Librechat within Docker.

Ollama is running fine on my local machine--if I run the following, I get a valid response as expected:

```
curl http://localhost:11434/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "phi3",
        "messages": [
            {
                "role": "system",
                "content": "You are a helpful assistant."
            },
            {
                "role": "user",
                "content": "Hello!"
            }
        ]
    }'
```

However I'm getting the following error within the `./logs` directory.

```
{"cause":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","message":"request to http://host.docker.internal:11434/v1/chat/completions failed, reason: connect ECONNREFUSED 172.17.0.1:11434","type":"system"},"level":"error","message":"[handleAbortError] AI response error; aborting request: Connection error.","stack":"Error: Connection error.\n    at OpenAI.makeRequest (/app/api/node_modules/openai/core.js:292:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChatCompletionStream._createChatCompletion (/app/api/node_modules/openai/lib/ChatCompletionStream.js:53:24)\n    at async ChatCompletionStream._runChatCompletion (/app/api/node_modules/openai/lib/AbstractChatCompletionRunner.js:314:16)"}

```

- [ ] 

### More Details

Here is my `librechat.yml` file:
---
# For more information, see the Configuration Guide:
# https://www.librechat.ai/docs/configuration/librechat_yaml

# Configuration version (required)
version: 1.0.9

# Cache settings: Set to true to enable caching
cache: true

endpoints:
  custom:
    - name: "Ollama"
      apiKey: "ollama"
      # use 'host.docker.internal' instead of localhost if running LibreChat in a docker container
      baseURL: "http://host.docker.internal:11434/v1/chat/completions" 
      models:
        default: [
          "codestral",
          "phi3",
          "mixtral:8x7b-instruct-v0.1-q4_1",
          ]
        # fetching list of models is supported but the `name` field must start
        # with `ollama` (case-insensitive), as it does in this example.
        fetch: true
      titleConvo: true
      titleModel: "current_model"
      summarize: false
      summaryModel: "current_model"
      forcePrompt: false
      modelDisplayLabel: "Ollama"

### What is the main subject of your question?

Endpoints

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
try to set the baseURL to : `http://host.docker.internal:11434/v1/`

**Comment by joelclimbsthings** [comment]
Thanks for the quick response, although (I should have mentioned) I had tried that as well. Same error:
```
{"cause":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","message":"request to http://host.docker.internal:11434/v1/chat/completions failed, reason: connect ECONNREFUSED 172.17.0.1:11434","type":"system"},"level":"error","message":"[handleAbortError] AI response error; aborting request: Connection error.","stack":"Error: Connection error.\n    at OpenAI.makeRequest (/app/api/node_modules/openai/core.js:292:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChatCompletionStream._createChatCompletion (/app/api/node_modules/openai/lib/ChatCompletionStream.js:53:24)\n    at async ChatCompletionStream._runChatCompletion (/app/api/node_modules/openai/lib/AbstractChatCompletionRunner.js:314:16)"}

```
