### ISSUE TITLE
[Bug]: TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by Zapzatron** [danny-avila/LibreChat#3015]
### What happened?

Got an error `TypeError [ERR_INVALID_ARG_TYPE]` when embedding LibreChat into Hugging Face Spaces.
[My space in hugging face](https://huggingface.co/spaces/Superchik/LibreChat)

### Steps to Reproduce

1. Embed a LibreChat space in your space
2. Wait for a build error
3. Get an error

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
===== Application Startup at 2024-06-09 19:03:13 =====


> LibreChat@0.7.2 backend
> cross-env NODE_ENV=production node api/server/index.js

node:buffer:319
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (node:buffer:319:9)
    at Object.<anonymous> (/app/api/server/utils/crypto.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/app/api/server/utils/index.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1358:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.14.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
Looks like you didn't provide all required `secrets`

**Comment by fuegovic** [comment]
Also, you should try cloning this template instead of our deployed instance, then customize it.

https://huggingface.co/spaces/LibreChat/template

**Comment by Zapzatron** [comment]
![image](https://github.com/danny-avila/LibreChat/assets/100136305/b5942f8a-0a8d-40f6-a7e6-724f6254e891)
Do I need to add these keys to the `secrets`?
