### ISSUE TITLE
[Bug]: Perplexity, Mistral, Message Payload Role Order Strictness

### ISSUE THREAD

**Issue by yuvaraj-06** [danny-avila/LibreChat#3048]
### What happened?

Unable to use Perplexity inside a existing chat thread where a modelspec option is being selected  but claude and gemini were working
![IMG_7891](https://github.com/danny-avila/LibreChat/assets/59510075/8bebde16-e4ae-4086-a689-ece5443dee42)

### Steps to Reproduce

Select a modelspec and then try to chose perplexity in between the chat thread 

### Relevant log output

```shell
<@986671659274600528> 

> `{
>   "code": 400,
>   "error": {
>     "code": 400,
>     "message": "After the (optional) system message(s), user and assistant roles should be alternating.",
>     "type": "invalid_message"
>   },
>   "headers": {
>     "cf-cache-status": "DYNAMIC",
>     "cf-ray": "88c835f9ee759681-SJC",
>     "connection": "keep-alive",
>     "content-length": "147",
>     "content-type": "application/json",
>     "date": "Fri, 31 May 2024 16:06:23 GMT",
>     "server": "cloudflare",
>     "set-cookie": "__cf_bm=Tqsoof0Od3ZnkX8kdljSGZhbGZA2sE5Exuu29468DG0-1717171583-1.0.1.1-NTIcyI677u74jICLpuzVRxxtpdYOWwh0G6W1LRzxh.k_Jqc3vX3EZNvF7_smyRiwyh__Rw7wfUTzaXagxh65KQ; path=/; expires=Fri, 31-May-24 16:36:23 GMT; domain=.perplexity.ai; HttpOnly; Secure; SameSite=None"
>   },
>   "level": "error",
>   "message": "[handleAbortError] AI response error; aborting request: 400 After the (optional) system message(s), user and assistant roles should be alternating.",
>   "stack": "Error: 400 After the (optional) system message(s), user and assistant roles should be alternating.\n    at APIError.generate (/app/api/node_modules/openai/error.js:45:20)\n    at OpenAI.makeStatusError (/app/api/node_modules/openai/core.js:263:33)\n    at OpenAI.makeRequest (/app/api/node_modules/openai/core.js:306:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ChatCompletionStream._createChatCompletion (/app/api/node_modules/openai/lib/ChatCompletionStream.js:53:24)\n    at async ChatCompletionStream._runChatCompletion (/app/api/node_modules/openai/lib/AbstractChatCompletionRunner.js:314:16)",
>   "status": 400,
>   "type": "invalid_message"
> }`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hollermay** [comment]
I can work on this issue, please assign,

**Comment by yuvaraj-06** [comment]
@danny-avila can you please assign to @hollermay

**Comment by danny-avila** [comment]
> @danny-avila can you please assign to @hollermay

Contributions don't work this way for this project. If you can work on the issue, just submit a PR @hollermay

**Comment by hollermay** [comment]
> > @danny-avila can you please assign to @hollermay
> 
> Contributions don't work this way for this project. If you can work on the issue, just submit a PR @hollermay 
> 
> Otherwise I will get to it when I can

Sure I'll raise one within a few days

**Comment by eroo36** [comment]
Bumping, but I have the same error using perplexity and system prompt included. It can answer once and next message it gives this error.

**Comment by danny-avila** [comment]
> Bumping, but I have the same error using perplexity and system prompt included. It can answer once and next message it gives this error.

This happens because perplexity is opinionated about where the system message should go, same with Mistral. I'm thinking of how to resolve this more broadly and not just for modelspecs.

**Comment by yuvaraj-06** [comment]
Hey I was able to fix ,

### Fix

Check this line of code [link](https://github.com/danny-avila/LibreChat/blob/2bb0842650685897c4149cadc1d5a7cb6d033f74/api/app/clients/OpenAIClient.js#L1161) change 

In the OpenAIClient.js

Previous :
`modelOptions.messages[0].role = 'user';`

Fix : 
`modelOptions.messages[0].role = 'system';`

**Comment by danny-avila** [comment]
> Hey I was able to fix ,
> ### Fix
> 
> Check this line of code [link](https://github.com/danny-avila/LibreChat/blob/2bb0842650685897c4149cadc1d5a7cb6d033f74/api/app/clients/OpenAIClient.js#L1161) change
> 
> In the OpenAIClient.js
> 
> Previous : `modelOptions.messages[0].role = 'user';`
> 
> Fix : `modelOptions.messages[0].role = 'system';`

This is not a one-size-fits-all solution, that's why it's not implemented. It's a deeper issue due to the strictness of the role order for those API providers.

**Comment by danny-avila** [comment]
System Messages are now always first in the chat history
