### ISSUE TITLE
[Bug]: user not found with email: myuser@example.com for openidId: myuser

### ISSUE THREAD

**Issue by awickham10** [danny-avila/LibreChat#3095]
### What happened?

After upgrading to 7.3, new OpenID users cannot login to LibreChat.

### Steps to Reproduce

1. Upgrade to 7.3
2. Identify a user that has not logged in before, and have them try to login using OpenID
3. User will see an Internal Server Error

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Relevant log output

```shell
2024-06-17T13:42:31.287Z info: [openidStrategy] user not found with openidId: myuser
2024-06-17T13:42:31.291Z info: [openidStrategy] user not found with email: myuser@example.com for openidId: myuser
2024-06-17T13:42:31.293Z error: [openidStrategy] login failed User validation failed: email: can't be blank
ValidationError: User validation failed: email: can't be blank
at Document.invalidate (/app/node_modules/mongoose/lib/document.js:3200:32)
at /app/node_modules/mongoose/lib/document.js:2993:17
at /app/node_modules/mongoose/lib/schematype.js:1368:9
at /opt/dynatrace/oneagent/agent/bin/1.291.121.20240531-083741/any/nodejs/nodejsagent.js:2248:48
at t.runInContext (/opt/dynatrace/oneagent/agent/bin/1.291.121.20240531-083741/any/nodejs/nodejsagent.js:2359:24)
at /opt/dynatrace/oneagent/agent/bin/1.291.121.20240531-083741/any/nodejs/nodejsagent.js:2248:18
at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Resolved now, thanks!
