### ISSUE TITLE
[Bug]: Azure OpenAI Assistants Downloads error

### ISSUE THREAD

**Issue by kezzzsVS** [danny-avila/LibreChat#3216]
### What happened?

Attempting to download generated files from Azure OpenAI Assistants results in a 500 Internal Server Error.
I can confirm that the generated file is available to download correctly from the Azure OpenAI Studio.

### Steps to Reproduce

1) Setup an assistant with Code Interpreter enabled
2) Use assistant and ask to generate a text file containing a random paragraph
3) The file will be generated
4) Click the download link with Chrome Dev Tools open, and check the network tab to observe the 500 Internal server error

### Relevant log output

```shell
/app/api/logs $ cat error-2024-06-27.log 
{"level":"error","message":"Error downloading file: Assistants API key not provided. Please provide it again.","stack":"Error: Assistants API key not provided. Please provide it again.\n    at initializeClient (/app/api/server/services/Endpoints/assistants/initializeClient.js:54:11)\n    at /app/api/server/routes/files/files.js:116:32\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}
/app/api/logs $
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/19303559/33d7ef1b-59c7-435c-850d-2bd0e96b3e79)

![image](https://github.com/danny-avila/LibreChat/assets/19303559/42fffb7a-4335-4bc6-a1ec-6c51529f9de7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tommartens1997** [comment]
The issue seems to be in: api/server/routes/files/files.js

LibreChat does not know we are using an Azure assistant.
I am new to the whole process of colaborating on GitHub so here are the required changes to solve the issue.

You should change:

```
const { initializeClien} = require('~/server/services/Endpoints/assistants');
```
into
```
const { initializeClient: initializeOpenAiClient } = require('~/server/services/Endpoints/assistants');
const { initializeClient: initializeAzureClient } = require('~/server/services/Endpoints/azureAssistants');
```

and also change
```
if (checkOpenAIStorage(file.source)) {
        req.body = { model: file.model };
        const { openai } = await initializeOpenAiClient({ req, res });
        logger.debug(`Downloading file ${file_id} from OpenAI`);
        passThrough = await getDownloadStream(file_id, openai);
        setHeaders();
        logger.debug(`File ${file_id} downloaded from OpenAI`);
        passThrough.body.pipe(res);
    } else {
      fileStream = getDownloadStream(file_id);
      setHeaders();
      fileStream.pipe(res);
    }
```
into the following
```
if (checkOpenAIStorage(file.source)) {
      logger.debug(`File source: ${file.source}`);
      if (file.source === FileSources.openai) {
        req.body = { model: file.model };
        logger.debug(`Downloading file ${file_id} from OpenAI`);
        const { openai } = await initializeOpenAiClient({ req, res });
        passThrough = await getDownloadStream(file_id, openai);
        setHeaders();
        logger.debug(`File ${file_id} downloaded from OpenAI`);
        passThrough.body.pipe(res);
      } else {
        req.body = { model: file.model };
        logger.debug(`Downloading file ${file_id} from Azure OpenAI`);
        const { openai } = await initializeAzureClient({ req, res });
        passThrough = await getDownloadStream(file_id, openai);
        setHeaders();
        logger.debug(`File ${file_id} downloaded from Azure OpenAI`);
        passThrough.body.pipe(res);
      }
    } else {
      fileStream = getDownloadStream(file_id);
      setHeaders();
      fileStream.pipe(res);
    }
```
