### ISSUE TITLE
[Bug]: RAG_OPENAI_BASEURL does not working properly

### ISSUE THREAD

**Issue by happyZYM** [danny-avila/LibreChat#3253]
### What happened?

When I tried to use a custom openai compatible endpoint for RAG, it doesn't work despite my effort to set the environment variable `RAG_OPENAI_BASEURL` to `https://my.openai.proxy/`.

Actually, the endpoint do work properly by testing as follows:
```
curl https://my.openai.proxy/v1/embeddings \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${KEY}" \
  -d '{
    "input": "Your text string goes here",
    "model": "text-embedding-3-small"
  }'
```

### Steps to Reproduce

1. set `RAG_OPENAI_BASEURL` and `RAG_OPENAI_API_KEY`
2. try to upload a file but failed

### Relevant log output

```shell
{"level":"error","message":"[/files] Error processing file: File embedding failed.","stack":"Error: File embedding failed.\n    at uploadVectors (/app/api/server/services/Files/VectorDB/crud.js:95:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async processFileUpload (/app/api/server/services/Files/process.js:348:7)\n    at async /app/api/server/routes/files/files.js:144:5"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by happyZYM** [comment]
Now I added `v1` to the end of the url, and by mannually calling OpenAIEmbeddings from langchain_openai, that ok. But in LibreChat it doesn't work.

**Comment by happyZYM** [comment]
I started a completed new LibreChat instance locally to avoid potential vectordb corrupt.

Now the log is:
```
rag_api           | 2024-07-03 14:20:34,451 - root - DEBUG - /embed - {'id': '66855d1bf0d066c7449c706d', 'username': 'ZZZ', 'provider': 'local', 'email': 'zhuangyumin@sjtu.edu.cn', 'iat': 1720016424, 'exp': 1720017324}
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_part_begin with no data
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_field with data[54:73]
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_value with data[75:100]
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_end with no data
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_headers_finished with no data
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_part_data with data[104:140]
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_part_end with no data
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_part_begin with no data
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_field with data[196:215]
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_value with data[217:272]
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_end with no data
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_field with data[274:286]
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_value with data[288:303]
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_header_end with no data
rag_api           | 2024-07-03 14:20:34,453 - multipart.multipart - DEBUG - Calling on_headers_finished with no data
rag_api           | 2024-07-03 14:20:34,454 - multipart.multipart - DEBUG - Calling on_part_data with data[307:88115]
rag_api           | 2024-07-03 14:20:34,455 - multipart.multipart - DEBUG - Calling on_part_data with data[0:305408]
rag_api           | 2024-07-03 14:20:34,457 - multipart.multipart - DEBUG - Calling on_part_data with data[0:262144]
rag_api           | 2024-07-03 14:20:34,457 - multipart.multipart - DEBUG - Calling on_part_data with data[0:222951]
rag_api           | 2024-07-03 14:20:34,457 - multipart.multipart - DEBUG - Calling on_part_data with data[0:1]
rag_api           | 2024-07-03 14:20:34,457 - multipart.multipart - DEBUG - Calling on_part_data with data[222952:226682]
rag_api           | 2024-07-03 14:20:34,458 - multipart.multipart - DEBUG - Calling on_part_data with data[0:1]
rag_api           | 2024-07-03 14:20:34,458 - multipart.multipart - DEBUG - Calling on_part_data with data[226683:262144]
rag_api           | 2024-07-03 14:20:34,458 - multipart.multipart - DEBUG - Calling on_part_data with data[0:137729]
rag_api           | 2024-07-03 14:20:34,459 - multipart.multipart - DEBUG - Calling on_part_data with data[0:1]
rag_api           | 2024-07-03 14:20:34,459 - multipart.multipart - DEBUG - Calling on_part_data with data[137730:177738]
rag_api           | 2024-07-03 14:20:34,459 - multipart.multipart - DEBUG - Calling on_part_data with data[0:1]
rag_api           | 2024-07-03 14:20:34,460 - multipart.multipart - DEBUG - Calling on_part_data with data[177739:262144]
rag_api           | 2024-07-03 14:20:34,464 - multipart.multipart - DEBUG - Calling on_part_data with data[0:262144]
rag_api           | 2024-07-03 14:20:34,465 - multipart.multipart - DEBUG - Calling on_part_data with data[0:262144]
rag_api           | 2024-07-03 14:20:34,466 - multipart.multipart - DEBUG - Calling on_part_data with data[0:176636]
rag_api           | 2024-07-03 14:20:34,467 - multipart.multipart - DEBUG - Calling on_part_data with data[0:1]
rag_api           | 2024-07-03 14:20:34,467 - multipart.multipart - DEBUG - Calling on_part_data with data[176637:262144]
rag_api           | 2024-07-03 14:20:34,468 - multipart.multipart - DEBUG - Calling on_part_data with data[0:262144]
rag_api           | 2024-07-03 14:20:34,469 - multipart.multipart - DEBUG - Calling on_part_data with data[0:262144]
rag_api           | 2024-07-03 14:20:34,470 - multipart.multipart - DEBUG - Calling on_part_data with data[0:15347]
rag_api           | 2024-07-03 14:20:34,470 - multipart.multipart - DEBUG - Calling on_part_data with data[0:1]
rag_api           | 2024-07-03 14:20:34,470 - multipart.multipart - DEBUG - Calling on_part_data with data[15348:37137]
rag_api           | 2024-07-03 14:20:34,470 - multipart.multipart - DEBUG - Calling on_part_data with data[0:1]
rag_api           | 2024-07-03 14:20:34,470 - multipart.multipart - DEBUG - Calling on_part_data with data[37138:62065]
rag_api           | 2024-07-03 14:20:34,470 - multipart.multipart - DEBUG - Calling on_part_data with data[0:1]
rag_api           | 2024-07-03 14:20:34,471 - multipart.multipart - DEBUG - Calling on_part_data with data[62066:114652]
rag_api           | 2024-07-03 14:20:34,471 - multipart.multipart - DEBUG - Calling on_part_end with no data
rag_api           | 2024-07-03 14:20:34,471 - multipart.multipart - DEBUG - Calling on_end with no data
rag_api           | 2024-07-03 14:20:34,707 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): openaipublic.blob.core.windows.net:443
chat-mongodb      | {"t":{"$date":"2024-07-03T14:21:12.697+00:00"},"s":"I",  "c":"WTCHKPT",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":{"ts_sec":1720016472,"ts_usec":697114,"thread":"1:0x740c073c6640","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":6,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 4, snapshot max: 4 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 39"}}}
chat-mongodb      | {"t":{"$date":"2024-07-03T14:22:12.712+00:00"},"s":"I",  "c":"WTCHKPT",  "id":22430,   "ctx":"Checkpointer","msg":"WiredTiger message","attr":{"message":{"ts_sec":1720016532,"ts_usec":712161,"thread":"1:0x740c073c6640","session_name":"WT_SESSION.checkpoint","category":"WT_VERB_CHECKPOINT_PROGRESS","category_id":6,"verbose_level":"DEBUG_1","verbose_level_id":1,"msg":"saving checkpoint snapshot min: 6, snapshot max: 6 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 39"}}}
rag_api           | 2024-07-03 14:22:48,398 - root - ERROR - HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x70c09c3ecac0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))
rag_api           | 2024-07-03 14:22:48,401 - root - INFO - Request POST http://rag_api:8000/embed - 200
LibreChat         | 2024-07-03 14:22:48 error: Error embedding file File embedding failed.
LibreChat         | 2024-07-03 14:22:48 error: [/files] Error processing file: File embedding failed.
```
