### ISSUE TITLE
[Bug]: Error 503: Issue Uploading Vectors and Processing Files

### ISSUE THREAD

**Issue by jaylee2019** [danny-avila/LibreChat#4741]
### What happened?

I'm encountering a 503 Service Unavailable error when attempting to upload vectors and process files in my application. Below is the detailed error log.
BTW, I tested the OpenAI API embeddig model by curl, it works.

### Steps to Reproduce

here is my RAG configuration in env
RAG_OPENAI_API_KEY=sk-xxxxx
EMBEDDINGS_PROVIDER=openai
EMBEDDINGS_MODEL=text-embedding-3-small

### Relevant log output

```shell
{
  "data": "",
  "headers": {
    "connection": "close",
    "content-length": "0",
    "proxy-connection": "close"
  },
  "level": "error",
  "message": "Error uploading vectors The request was made and the server responded with a status code that falls out of the range of 2xx: Request failed with status code 503. Error response data:\n",
  "status": 503
}
```

### Screenshots

![image](https://github.com/user-attachments/assets/b8b50701-0bcd-4528-a4cf-9d42068f696e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaylee2019** [comment]
Error Logs:
{
  "data": "",
  "headers": {
    "connection": "close",
    "content-length": "0",
    "proxy-connection": "close"
  },
  "level": "error",
  "message": "Error uploading vectors The request was made and the server responded with a status code that falls out of the range of 2xx: Request failed with status code 503. Error response data:\n",
  "status": 503
}
{
  "level": "error",
  "message": "[/files] Error processing file: Request failed with status code 503",
  "stack": "Error: Request failed with status code 503\n    at uploadVectors (/app/api/server/services/Files/VectorDB/crud.js:102:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async processFileUpload (/app/api/server/services/Files/process.js:366:7)\n    at async /app/api/server/routes/files/files.js:230:5"
}
