### ISSUE TITLE
[Bug]: LibreChat no longer shows login form, can't use it

### ISSUE THREAD

**Issue by JeongJuhyeon** [danny-avila/LibreChat#5135]
### What happened?

Console only shows this error which does not necessarily seem related:

```
sw.js:1 Uncaught (in promise) add-to-cache-list-conflicting-entries: add-to-cache-list-conflicting-entries :: [{"firstEntry":"https://DOMAIN/assets/apple-touch-icon-180x180.png","secondEntry":"https://DOMAINHERE/assets/apple-touch-icon-180x180.png?__WB_REVISION__=492ee09f6a0dfd5a3c1250a23679e6eb"}]
    at I.addToCacheList (https://DOMAINHERE/sw.js:1:12293)
    at I.precache (https://DOMAINHERE/sw.js:1:11924)
    at https://DOMAINHERE/sw.js:1:14835
    at https://DOMAINHERE/sw.js:1:14847
    at https://DOMAINHERE/sw.js:1:565
```
 Where DOMAINHERE is the domain it runs on. 
The console does not print anything else.
This started all of a sudden, without making any changes to the server/setup.

Things tried:
- Updating to the latest version (did not help)
- Private window to avoid caching impact (did not help)

Another thing: If I go to the root of the domain (without `/login`), I get redirected on `/c/new` (which is blank) and get stuck there. So the above screenshot and console log comes from going to `../login` directly.

### Steps to Reproduce

A: Visit `domain/login`
B (getting stuck on /new/c): Visit domain root

### What browsers are you seeing the problem on?

Chrome

### Screenshots

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/dad02245-1981-4980-a702-9646ddb1c092" />

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JeongJuhyeon** [comment]
Browser update fixed it
