### ISSUE TITLE
[Bug]: Request can't have PreviousMessages for an existing conversation.

### ISSUE THREAD

**Issue by riverai** [danny-avila/LibreChat#657]
### What happened?

>Oops! Som
/ething went wrong. Please try again in a few moments. Here's the specific error message we encountered: InvalidRequest: Request can't have PreviousMessages for an existing conversation.

This has happened to me many times.
It usually **comes up in the second round of dialog in a conversation.**
After I say the second words, the bing response becomes this error.

And, this has a side effect.

If I refresh the page, I'll find that the entire conversation has disappeared and only this error message will still be there.
It appears that the data is not saved to the database.

But in fact the previous conversation is still valuable

### Steps to Reproduce

1 bing Creativity Mode, no jailbreak. Using  context
2 Submitting my first round of conversations
3 bing replied to my content
4  submitting my 2nd question
5 Oops! Something went wrong. Please try again in a few moments. Here's the specific error message we encountered: InvalidRequest: Request can't have PreviousMessages for an existing conversation.

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
2023-07-17 01:57:46 Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.
2023-07-17 01:57:46     at WebSocket.<anonymous> (file:///app/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:487:36)
2023-07-17 01:57:46     at WebSocket.emit (node:events:525:35)
2023-07-17 01:57:46     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20)
2023-07-17 01:57:46     at Receiver.emit (node:events:513:28)
2023-07-17 01:57:46     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:541:14)
2023-07-17 01:57:46     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:459:17)
2023-07-17 01:57:46     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:158:22)
2023-07-17 01:57:46     at Receiver._write (/app/node_modules/ws/lib/receiver.js:84:10)
2023-07-17 01:57:46     at writeOrBuffer (node:internal/streams/writable:392:12)
2023-07-17 01:57:46     at _write (node:internal/streams/writable:333:10)
2023-07-17 01:57:46 Error: InvalidRequest: Request can't have PreviousMessages for an existing conversation.
2023-07-17 01:57:46     at WebSocket.<anonymous> (file:///app/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:487:36)
2023-07-17 01:57:46     at WebSocket.emit (node:events:525:35)
2023-07-17 01:57:46     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20)
2023-07-17 01:57:46     at Receiver.emit (node:events:513:28)
2023-07-17 01:57:46     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:541:14)
2023-07-17 01:57:46     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:459:17)
2023-07-17 01:57:46     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:158:22)
2023-07-17 01:57:46     at Receiver._write (/app/node_modules/ws/lib/receiver.js:84:10)
2023-07-17 01:57:46     at writeOrBuffer (node:internal/streams/writable:392:12)
2023-07-17 01:57:46     at _write (node:internal/streams/writable:333:10)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
I’m sure the messages are still there. Hover over the single message you see and check if any cursors appear to switch through different message branches. 

As for the specific issue, I will investigate but most likely a dependency issue (as your logs even show “ node_modules/@waylaidwanderer/ ”).

Since access to bing is very hacky, especially with jailbreak, issues like this are to be expected.

**Comment by danny-avila** [comment]
Can you explain this more? 

>the second round of dialog in a conversation.

Do you mean when you return to a previously had convo?

**Comment by riverai** [comment]
> 

Let me try to explain.
This actually represents the second paragraph I typed.

I:some words..
bing: some words..
I:some words 
bing:Something went wrong. Please try again in a few moments. Here's the specific error message we encountered: InvalidRequest: Request can't have PreviousMessages for an existing conversation.


At this point I was not setting  bing to jailbreaking. Because I found that jailbreaking seemed to interfere with the context  I had written myself.

**Comment by riverai** [comment]
![image](https://github.com/danny-avila/LibreChat/assets/3251548/f398f29d-60a3-443c-800d-a1d8ce1ed5fc)
Here's a screenshot

**Comment by riverai** [comment]
I tested it many times.

This problem only occurs in modes that do not jailbreak the bing. If I activate the jailbreak mode, this problem does not happen.
But whenever I activate the jailbreak mode, the prompt words I enter myself almost always do nothing.

🥲
