### ISSUE TITLE
[Bug]: Error occurs when 'Copy Code' button is clicked

### ISSUE THREAD

**Issue by SphaeroX** [danny-avila/LibreChat#693]
### What happened?

Hi,

I hope this message finds you well. I wanted to report an issue that I encountered while using your project. When I click the 'Copy Code' button, I receive a browser error with the following details:

> CodeBlock.tsx:25  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'writeText')
>     at onClick (CodeBlock.tsx:25:35)
>     at Object.mD (vendor-e5aad502.js:37:9864)
>     at vD (vendor-e5aad502.js:37:10018)
>     at ED (vendor-e5aad502.js:37:10075)
>     at Y8 (vendor-e5aad502.js:37:31482)
>     at p_ (vendor-e5aad502.js:37:31899)
>     at vendor-e5aad502.js:37:36812
>     at qE (vendor-e5aad502.js:40:36956)
>     at QS (vendor-e5aad502.js:37:8999)
>     at f4 (vendor-e5aad502.js:37:33186)

It seems that there is an unhandled TypeError on line 25 of the CodeBlock.tsx file, where it tries to read properties of an undefined object while attempting to execute the writeText operation.

I believe this issue might be affecting the functionality of the application, and it would be great if you could look into it and provide a possible solution. If there are any additional details or steps required to reproduce the problem, please let me know.

### Steps to Reproduce

Try Copy Code

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
CodeBlock.tsx:25  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'writeText')
    at onClick (CodeBlock.tsx:25:35)
    at Object.mD (vendor-e5aad502.js:37:9864)
    at vD (vendor-e5aad502.js:37:10018)
    at ED (vendor-e5aad502.js:37:10075)
    at Y8 (vendor-e5aad502.js:37:31482)
    at p_ (vendor-e5aad502.js:37:31899)
    at vendor-e5aad502.js:37:36812
    at qE (vendor-e5aad502.js:40:36956)
    at QS (vendor-e5aad502.js:37:8999)
    at f4 (vendor-e5aad502.js:37:33186)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SphaeroX** [comment]
closed, i didnt use https....
