### ISSUE TITLE
[Bug]: Bing can't carry out the second round of conversation

### ISSUE THREAD

**Issue by Passerby1011** [danny-avila/LibreChat#727]
### Contact Details

passerbywtj@gmail.com

### What happened?

My bing can't do the second round of conversations, Sydney does, and it works fine when I'm on the web
Translation：我的bing无法进行第二轮对话，而Sydney却可以，我在网页时也可以正常使用。

### Steps to Reproduce

Normal conversation.

### Relevant log output

```shell
LibreChat         | ask log {
LibreChat         |   userMessage: {
LibreChat         |     messageId: '0a9e8d70-d920-43ec-9365-c0f0fcf2e56f',
LibreChat         |     sender: 'User',
LibreChat         |     text: '介绍一下你自己',
LibreChat         |     parentMessageId: 'df3f49f2-8b95-492a-aa22-271edb362e40',
LibreChat         |     conversationId: '454700fa-69a1-4f67-8679-7c54c1e43fa5',
LibreChat         |     isCreatedByUser: true
LibreChat         |   },
LibreChat         |   endpointOption: {
LibreChat         |     jailbreak: false,
LibreChat         |     systemMessage: null,
LibreChat         |     context: null,
LibreChat         |     conversationSignature: 'RYpmWDt7Uy6yYrSuZpcs45bbDjTK4m/xri+9VlznMeo=',
LibreChat         |     clientId: '1055518800064708',
LibreChat         |     invocationId: 1,
LibreChat         |     toneStyle: 'creative',
LibreChat         |     token: null
LibreChat         |   },
LibreChat         |   conversationId: '454700fa-69a1-4f67-8679-7c54c1e43fa5'
LibreChat         | }
chat-meilisearch  | [2023-07-29T15:03:51Z INFO  actix_web::middleware::logger] 172.31.0.4 "GET /indexes/convos/documents/454700fa-69a1-4f67-8679-7c54c1e43fa5 HTTP/1.1" 200 83 "-" "undici" 0.004137
chat-meilisearch  | [2023-07-29T15:03:51Z INFO  actix_web::middleware::logger] 172.31.0.4 "POST /indexes/messages/documents HTTP/1.1" 202 136 "-" "undici" 0.016092
LibreChat         | bing options {
LibreChat         |   conversationId: '51D|BingProd|9306B780CDE3D8F65A6556C3A19D242B6BCEE137A0ADCF58EEDC61C567E325DA',
LibreChat         |   context: null,
LibreChat         |   systemMessage: null,
LibreChat         |   parentMessageId: 'df3f49f2-8b95-492a-aa22-271edb362e40',
LibreChat         |   toneStyle: 'creative',
LibreChat         |   onProgress: [Function: wrapper],
LibreChat         |   clientOptions: { features: { genImage: [Object] } },
LibreChat         |   conversationSignature: 'RYpmWDt7Uy6yYrSuZpcs45bbDjTK4m/xri+9VlznMeo=',
LibreChat         |   clientId: '1055518800064708',
LibreChat         |   invocationId: 1
LibreChat         | }
chat-meilisearch  | [2023-07-29T15:03:51Z INFO  index_scheduler::batch] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 15 }
chat-meilisearch  | [2023-07-29T15:03:51Z INFO  index_scheduler] A batch of tasks was successfully completed.
LibreChat         | Error: Unexpected server response: 200
LibreChat         |     at ClientRequest.<anonymous> (/app/node_modules/ws/lib/websocket.js:888:7)
LibreChat         |     at ClientRequest.emit (node:events:513:28)
LibreChat         |     at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
LibreChat         |     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
LibreChat         |     at TLSSocket.socketOnData (node:_http_client:535:22)
LibreChat         |     at TLSSocket.emit (node:events:513:28)
LibreChat         |     at addChunk (node:internal/streams/readable:324:12)
LibreChat         |     at readableAddChunk (node:internal/streams/readable:297:9)
LibreChat         |     at Readable.push (node:internal/streams/readable:234:10)
LibreChat         |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
LibreChat         | Error: Unexpected server response: 200
LibreChat         |     at ClientRequest.<anonymous> (/app/node_modules/ws/lib/websocket.js:888:7)
LibreChat         |     at ClientRequest.emit (node:events:513:28)
LibreChat         |     at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
LibreChat         |     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
LibreChat         |     at TLSSocket.socketOnData (node:_http_client:535:22)
LibreChat         |     at TLSSocket.emit (node:events:513:28)
LibreChat         |     at addChunk (node:internal/streams/readable:324:12)
LibreChat         |     at readableAddChunk (node:internal/streams/readable:297:9)
LibreChat         |     at Readable.push (node:internal/streams/readable:234:10)
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/63802758/c34f4cef-b19f-42aa-b779-88f512020041)

![image](https://github.com/danny-avila/LibreChat/assets/63802758/2d1cee21-9b9d-4908-961f-bf1ac50fb938)

![image](https://github.com/danny-avila/LibreChat/assets/63802758/cad60ef1-27e9-4ac1-8900-20afdf6a8110)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fuegovic** [comment]
Try generating a new token from the edge browser (use the full cookie string method):
https://github.com/danny-avila/LibreChat/issues/370#issuecomment-1560382302

This might help with your problem
