### ISSUE TITLE
[Need help]: New Bing requires captcha

### ISSUE THREAD

**Issue by xma7-cn** [danny-avila/LibreChat#793]
### Contact Details

gallon66@live.com

### What happened?

New Bing requires captcha, but I found nowhere to finish it, including checking the console logs of LibreChat.

### Steps to Reproduce

1. Entered my cookies already
2. Kept refereshing several times
3. tried to finish the captcha in my own pc's browser with the same account, resent the message, and nothing changed

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
The Website feedback shows: "Something went wrong. Please try again in a few moments. Here's the specific error message we encountered: CaptchaChallenge: User needs to solve CAPTCHA to continue."
The Console logs shows: "
ask log {
  userMessage: {
    messageId: 'd89c36bb-702b-45a3-8607-e328e978e674',
    sender: 'User',
    text: 'hihi',
    parentMessageId: '00000000-0000-0000-0000-000000000000',
    conversationId: '1ee36dee-0a98-443d-a798-d35be86f939b',
    isCreatedByUser: true
  },
  endpointOption: {
    jailbreak: false,
    systemMessage: null,
    context: null,
    conversationSignature: null,
    clientId: null,
    invocationId: 1,
    toneStyle: 'balanced',
    token: ''
  },
  conversationId: '1ee36dee-0a98-443d-a798-d35be86f939b'
}
bing options {
  conversationId: '1ee36dee-0a98-443d-a798-d35be86f939b',
  context: null,
  systemMessage: null,
  parentMessageId: '00000000-0000-0000-0000-000000000000',
  toneStyle: 'balanced',
  onProgress: [Function: wrapper],
  clientOptions: { features: { genImage: [Object] } }
}
Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.
    at WebSocket.<anonymous> (file:///app/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:491:36)
    at WebSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/app/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/app/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
Error: CaptchaChallenge: User needs to solve CAPTCHA to continue.
    at WebSocket.<anonymous> (file:///app/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:491:36)
    at WebSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/app/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/app/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
"
```

### Screenshots

![屏幕截图 2023-08-12 213339](https://github.com/danny-avila/LibreChat/assets/14000142/d6cc071d-ac85-4d6e-96b0-191c5b8b80e9)
![image](https://github.com/danny-avila/LibreChat/assets/14000142/89da66b1-8cce-4e46-9931-88fd34b03973)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
Several users have had this issue already, with many different solutions. The issues with bing often come because of IP/location/extended use, and it's not an officially supported method

**Here are some potential solutions I found from [the discord thread](https://discord.com/channels/1086345563026489514/1131849669874557049) on the issue:**
>when you edit the .env file you need to rebuild Librechat (which I didn't until now)
So after getting the full cookie string, open your terminal in the Librechat folder and go with docker-compose build e docker-compose up

>Visit this link in Edge https://www.bing.com/turing/captcha/challenge
then go to bing
log in
https://www.bing.com/search?q=Bing+AI&showconv=1&Form=hpcodx
got to this link
and get the cookies
and add it on LibereChat bing token
it will work
must be in edge
https://github.com/danny-avila/LibreChat/issues/370#issuecomment-1560382302
this is how to get cookies
its working nice for me both Sydney and bing

**If you have trouble opening the discord link, [join the discord server first](https://discord.gg/NGaa9RPCft)**
