### ISSUE TITLE
[Bug]: Anthropic: "maxOutputTokens: extra fields not permitted"

### ISSUE THREAD

**Issue by Outcats** [danny-avila/LibreChat#932]
### Contact Details

robmt67@hotmail.com

### What happened?

When trying to send a message to Claude via the Anthropic API, I get the following error:

`Something went wrong. Here's the specific error message we encountered: {"error":{"type":"invalid_request_error","message":"maxOutputTokens: extra fields not permitted"}}`

This is on version v0.5.8 both on an existing copy of your code as well as on a fresh git pull + clean and re execution of "docker-compose up"

This is also happened both via adding the API Key via the GUI front end and as well adding it into the .env file and re-building the docker image.

I have also generated a new API key which is getting the same error.

I am running this on Docker Desktop on Windows Server 2022 Standard

### Steps to Reproduce

1. Log into GUI
2. Select Anthropic from the list
3. Type a message and press enter
4. Receive error

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
2023-09-12 09:28:18 ask log
2023-09-12 09:28:18 {
2023-09-12 09:28:18   text: 'test',
2023-09-12 09:28:18   conversationId: '96104d58-cc1d-4353-9438-bb18a0976ab2',
2023-09-12 09:28:18   endpointOption: {
2023-09-12 09:28:18     endpoint: 'anthropic',
2023-09-12 09:28:18     modelLabel: null,
2023-09-12 09:28:18     promptPrefix: null,
2023-09-12 09:28:18     modelOptions: {
2023-09-12 09:28:18       model: 'claude-2',
2023-09-12 09:28:18       temperature: 1,
2023-09-12 09:28:18       maxOutputTokens: 1024,
2023-09-12 09:28:18       topP: 0.7,
2023-09-12 09:28:18       topK: 5
2023-09-12 09:28:18     }
2023-09-12 09:28:18   }
2023-09-12 09:28:18 }
2023-09-12 09:28:19 BadRequestError: {"error":{"type":"invalid_request_error","message":"maxOutputTokens: extra fields not permitted"}}
2023-09-12 09:28:19     at APIError.generate (/app/node_modules/@anthropic-ai/sdk/error.js:42:14)
2023-09-12 09:28:19     at Anthropic.makeStatusError (/app/node_modules/@anthropic-ai/sdk/core.js:221:29)
2023-09-12 09:28:19     at Anthropic.request (/app/node_modules/@anthropic-ai/sdk/core.js:257:24)
2023-09-12 09:28:19     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-09-12 09:28:19     at async AnthropicClient.sendCompletion (/app/api/app/clients/AnthropicClient.js:283:22)
2023-09-12 09:28:19     at async AnthropicClient.sendMessage (/app/api/app/clients/BaseClient.js:479:45)
2023-09-12 09:28:19     at async /app/api/server/routes/ask/anthropic.js:92:22 {
2023-09-12 09:28:19   status: 400,
2023-09-12 09:28:19   headers: {
2023-09-12 09:28:19     'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
2023-09-12 09:28:19     'content-length': '98',
2023-09-12 09:28:19     'content-type': 'application/json',
2023-09-12 09:28:19     date: 'Tue, 12 Sep 2023 08:28:19 GMT',
2023-09-12 09:28:19     'request-id': 'ef1d899f5ce1f401248822ef7d1722ed5c9303c9cbcfd3d13c2d55778b641bad',
2023-09-12 09:28:19     server: 'Google Frontend',
2023-09-12 09:28:19     via: '1.1 google',
2023-09-12 09:28:19     'x-cloud-trace-context': '42d35d3db1fb887e9a81e31fa0018b0c',
2023-09-12 09:28:19     'x-should-retry': 'false'
2023-09-12 09:28:19   },
2023-09-12 09:28:19   error: {
2023-09-12 09:28:19     error: {
2023-09-12 09:28:19       type: 'invalid_request_error',
2023-09-12 09:28:19       message: 'maxOutputTokens: extra fields not permitted'
2023-09-12 09:28:19     }
2023-09-12 09:28:19   }
2023-09-12 09:28:19 }
```

### Screenshots

![image](https://github.com/danny-avila/LibreChat/assets/11628565/842b013e-d7fe-4961-bb98-3fa5c0bf1ebd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danny-avila** [comment]
No problem on my end, which is weird.


![image](https://github.com/danny-avila/LibreChat/assets/110412045/e270c66c-3410-4971-a3a5-4338ab141db5)


```
{
  prompt: '\n\nHuman:\nhi\n\n\nAssistant:\nHello!\n\n\nHuman:\nwhats up\n\n\nAssistant:\n',
  model: 'claude-2',
  stream: true,
  max_tokens_to_sample: 1024,
  metadata: { user_id: '64fd734a81cf513500537e72' },
  temperature: 1,
  maxOutputTokens: 1024,
  topP: 0.7,
  topK: 5,
  stop: [ '||>', '\n\nHuman:', '<|diff_marker|>' ]
}
Stream {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
    [Symbol(Response internals)]: {
      url: 'https://api.anthropic.com/v1/complete',
      status: 200,
      statusText: 'OK',
      headers: [Headers],
      counter: 0
    }
  },
  controller: AbortController { signal: AbortSignal { aborted: false } },
  decoder: SSEDecoder { event: null, data: [], chunks: [] },
  responseHeaders: {
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    'cache-control': 'no-cache',
    'content-type': 'text/event-stream; charset=utf-8',
    date: 'Tue, 12 Sep 2023 13:32:38 GMT',
    'request-id': 'b9c13142c44708a47824d7aed04ea1e2ab00b4223719cda4478060eb69630dc3',
    server: 'Google Frontend',
    'transfer-encoding': 'chunked',
    via: '1.1 google',
    'x-accel-buffering': 'no'
  }
}
```

**Comment by danny-avila** [comment]
I'll fix this today as `maxOutputTokens` is being sent in the payload but it's weird that it doesn't cause an issue for me.

**Comment by Outcats** [comment]
Hey I pulled your update and now getting a different error:

![image](https://github.com/danny-avila/LibreChat/assets/11628565/ec35ff4e-3901-4764-9cf3-cbbb939324dc)

**Comment by danny-avila** [comment]
should be fixed now
